openapi: 3.1.0
x-stoplight:
  id: wpy4taupm06jq
info:
  title: Crm
  version: '1.0'
  license:
    url: 'https://opensource.org/licenses/MIT'
    name: MIT
  contact:
    email: dataops@flex.one
    name: Dataops
    url: 'https://www.flex.one'
  description: Endpoints for Crm Integrations
  summary: Crm Integrations
servers:
  - url: 'http://localhost:3000'
    description: Local
  - url: 'https://platform.flexbase.dev'
    description: Development
  - url: 'https://platform.flex.one'
    description: Production
paths:
  '/crm/hubspot/contacts/persons/{personId}/sync':
    parameters:
      - $ref: '#/components/parameters/personId'
    get:
      summary: Sync Person Data to Hubspot Contacts
      tags:
        - Hubspot
      operationId: getCrmHubspotContactsPersonIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotContact.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: 33i9xp6hmxdzs
  '/crm/hubspot/companies/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Business Data to Hubspot Contacts
      tags:
        - Hubspot
      operationId: getCrmHubspotCompaniesBusinessIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotCompany.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: qc86yhav2ksuz
  '/crm/hubspot/underwriting/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Business Data to Hubspot Underwriting
      tags:
        - Hubspot
      operationId: getCrmHubspotUnderwritingBusinessIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotUnderwriting.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: h0r2z1pspfvtk
  '/crm/hubspot/deals/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Business Data to Hubspot Deals
      tags:
        - Hubspot
      operationId: getCrmHubspotDealsBusinessIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotDeal.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: ht300mzigyzww
  '/crm/hubspot/onboarding/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Business Data to Hubspot Onboarding
      tags:
        - Hubspot
      operationId: getCrmHubspotOnboardingBusinessIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotOnboarding.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: fyrw0ikggd6w2
  '/crm/hubspot/account-management/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Business Data to Hubspot Account Management
      tags:
        - Hubspot
      operationId: getCrmHubspotAccountManagementBusinessIdSync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotAccountManagement.yaml
                    x-stoplight:
                      id: cb5kdwg5miv0x
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: nqntq15p88kl1
      description: ''
      x-stoplight:
        id: 55il9v4n5cg1c
  '/crm/hubspot/monthly-spend/businesses/{businessId}/sync':
    parameters:
      - $ref: '#/components/parameters/businessId'
    get:
      summary: Sync Spend Data to Hubspot MonthlySpend
      tags:
        - Hubspot
      operationId: getCrmHubspotMonthlySpendBusinessIdSync
      parameters:
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ./models/HubspotMonthlySpend.yaml
                    x-stoplight:
                      id: ty2qpvf5lap0y
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: kaldq15p11kp2
      description: ''
      x-stoplight:
        id: 36poqwayhj8gu
  /crm/hubspot/contacts/syncAll:
    parameters: []
    get:
      summary: Sync All Persons Data to Hubspot Contacts
      tags:
        - Hubspot
      operationId: getCrmHubspotContactsSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotContact.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: 7ojbn6e2uepba
  /crm/hubspot/companies/syncAll:
    parameters: []
    get:
      summary: Sync All Businesses Data to Hubspot Companies
      tags:
        - Hubspot
      operationId: getCrmHubspotCompaniesSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotCompany.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: u7sh22v705t8f
  /crm/hubspot/underwriting/syncAll:
    parameters: []
    get:
      summary: Sync All Businesses Data to Hubspot Underwriting
      tags:
        - Hubspot
      operationId: getCrmHubspotUnderwritingSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotUnderwriting.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: 9fon58nsmrr6e
  /crm/hubspot/deals/syncAll:
    parameters: []
    get:
      summary: Sync All Businesses Data to Hubspot Deals
      tags:
        - Hubspot
      operationId: getCrmHubspotDealsSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotDeal.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: fiqfl7jhk1zn9
  /crm/hubspot/onboarding/syncAll:
    parameters: []
    get:
      summary: Sync All Business Data to Hubspot Onboarding
      tags:
        - Hubspot
      operationId: getCrmHubspotOnboardingSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotOnboarding.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: 2i1yahou72gn7
  /crm/hubspot/account-management/syncAll:
    parameters: []
    get:
      summary: Sync All Businesses Data to Hubspot Account Management
      tags:
        - Hubspot
      operationId: getCrmHubspotAccountManagementSyncAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: mk9k36e4dxasv
                  data:
                    type: array
                    x-stoplight:
                      id: dq6gfvxj4xckp
                    items:
                      $ref: ./models/HubspotAccountManagement.yaml
                      x-stoplight:
                        id: rfzyfdmtvtwnr
      description: ''
      x-stoplight:
        id: 8qck7oonutqfz
  /crm/hubspot/monthly-spend/syncAll:
    parameters: []
    get:
      summary: Sync All Spend Data to Hubspot MonthlySpend
      tags:
        - Hubspot
      operationId: getCrmHubspotMonthlySpendSyncAll
      parameters:
        - $ref: '#/components/parameters/startDate'
        - $ref: '#/components/parameters/endDate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    $ref: ./models/PaginationMetadata.yaml
                    x-stoplight:
                      id: n3k2mfad8e4kt
                  data:
                    type: array
                    x-stoplight:
                      id: pqf042mfv8za9
                    items:
                      $ref: ./models/HubspotMonthlySpend.yaml
                      x-stoplight:
                        id: pflqrnf9j1rt5
      description: ''
      x-stoplight:
        id: u6tlw9zf9zstu
components:
  schemas: {}
  securitySchemes:
    token:
      type: http
      scheme: bearer
  parameters:
    personId:
      name: personId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The person identifier
    businessId:
      name: businessId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The business identifier
    startDate:
      name: startDate
      in: query
      required: true
      schema:
        type: string
        format: date
      description: Minimum date to include in response
    endDate:
      name: endDate
      in: query
      required: true
      schema:
        type: string
        format: date
      description: Maximum date to include in response
security:
  - token: []
tags:
  - name: Crm
    description: Crm
  - name: Hubspot
    description: Hubspot
x-internal: true
